[package]
name = "floccus_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
# quick-xml = {  version = "0.36.1", features = ["serde", "serialize"] }
# crossterm = "0.28.1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
git2 = "0.19"
quick-xml = {  version = "0.36", features = ["serde", "serialize"] }
directories = "5.0"
thiserror = "1.0"